### ISSUE TITLE
Bug : Random Sound Distortion / Sync Issue

### ISSUE THREAD

**Issue by StagLifeSL** [p1pkin/demul#353]
Tested with the latest 201215 build, this issue has appeared in earlier builds as well.
While playing a game, sound distortions can be briefly and randomly heard with micro visual slowdowns. Replicating this at an exact point of gameplay seems to be very difficult because of it's random nature, but this issue is frequent.
I noticed that this issue happens more frequently when vsync option is selected, although it happens when vsync is not selected as well.

**Comment by p1pkin** [comment]
emulation of hardware works like single clockwork, so if you have stall in some 'cog' - the whole mechanism will be stopped during what time. including sound, so you hear distortion or some other artifacts.
usually the cause is lack of PC power, or shaders compilation during first game run, or particular scenes in the game.
anyway, this is how this (and not only this) emulator works, don't think this will be changed in foreseeable future

**Comment by StagLifeSL** [comment]
Thanks for replying p1pkin, can you provide me with the minimum and the recommended PC specs for optimal performance ?

**Comment by p1pkin** [comment]
have no idea. all I know is how it works on my PC, on which this emulator was developed. so it's up on users to figure out how it works on various PC configurations.

**Comment by nicolasbocquet** [comment]
Got the same issue with :
i7 7700HQ CPU 2.80GHz
8go ram
NVIDIA GeForce GTX 1050

Easily and very (very) frequently reproduced with DEMUL alpha 0.7 and Phantasy Star Online Ver.2 (EU version), vsync ON.

**Comment by p1pkin** [comment]
typically it can be shaders compilation time, during it will happen notable stall for fraction of second (doesn't matter whatever powerful PC you have). but it happen only at start of some game scene, and usually not happened anymore.
so "very very frequently" smells like video drivers power management issue.
create profile for Demul in Nvidia drivers and disable power management like shown in article below, also make sure Demul run on NV GPU, not on embedded in CPU video core.
http://nvidia.custhelp.com/app/answers/detail/a_id/3130/~/setting-power-management-mode-from-adaptive-to-maximum-performance

same tweaks required for many other 3D emulator and older games if you have new powerful video card (yes, the more powerful GPU you have - then more slowdowns in old games or emulators will happen)

**Comment by nicolasbocquet** [comment]
Excellent !
That's **exactly** what was triggering the issue !

Thanks to you, it's working like a charm now.

**Comment by p1pkin** [comment]
welcome
