### ISSUE TITLE
Bug: Resident Evil 2 wipes any connected VMUs

### ISSUE THREAD

**Issue by IlDucci** [p1pkin/demul#358]
What steps will reproduce the problem?
1. Load Resident Evil 2 (PAL, not tested on NTSC)
2. Wait until the game says "Checking Visual Memory"
3. Any VMUs that are connected and enabled in the Maple Device Manager will be formatted, erasing any saved games. Any VMUs that are selected in the Maple Device Manager but unplugged (NONE option) will be spared.

What is the expected output?
The emulator/game won't wipe any VMUs, so we can load a saved game.

What version of the product are you using? On what operating system?
Tested on Demul 0.5.8.2 and 0.7.0 beta 20/12/2015.

**Comment by p1pkin** [comment]
not tested, but I'd bet its the same as https://github.com/p1pkin/demul/issues/145
try use VMS instead of VMU as workaround (in term of Demul its VMU without LCD and clock)
proper fix will be in next build

**Comment by IlDucci** [comment]
Guess not. Switching VMS to VMU isn't fixing things: The VMS is wiped too.

**Comment by p1pkin** [comment]
can you share your VMU saves (memsaves folder) and .ini files in emulator's root folder ?
bug doesn't happens for me using US version, I'll get PAL one and check it too.

**Comment by IlDucci** [comment]
[RESIDENTEVIL2.zip](https://github.com/p1pkin/demul/files/76320/RESIDENTEVIL2.zip)
[demul070.zip](https://github.com/p1pkin/demul/files/76321/demul070.zip)

The current testing happens with just this save, which is out of the memsaves folder.

**Comment by p1pkin** [comment]
ok, problem is in yours VMU binary (RESIDENTEVIL2.BIN), game thinks its bad/wrong and format it
where/how do you get it ?
but you can use saves from there - boot into BIOS, and copy saves to some other empty VMU. after doing this it will be accepted fine by the game.

in general, WinCE games quite strict to various things, so if some VMU-editor program (which you use to import particular saves into VMS binary) makes even single byte wrong and not same as real Dreamcast does - there is chances it will be rejected by game

**Comment by IlDucci** [comment]
These are savegames from Dreamcast, exported via DreamShell, then El Bucaneros' tool, and then VMU Explorer.

**Comment by p1pkin** [comment]
well, then VMU Explorer is the problem. probably it does several bytes in service area not the same as normal BIOS-formatted VMU, so game thinks this memory card is damaged or something like that.

**Comment by p1pkin** [comment]
anyway, game accepted fine your's saved games, after I copied them to other VMU using BIOS, so I close this.

**Comment by IlDucci** [comment]
Didn't knew WinCE was so picky. Thanks.

**Comment by p1pkin** [comment]
yes, it is. welcome.
