### ISSUE TITLE
Club Kart European session (2003)(REV.A) NAOMI

### ISSUE THREAD

**Issue by RAMBO123654** [p1pkin/demul#365]
Hello.
My probleme is Brake and accel no work in test mode but work in game.
![post-133-0-75467900-1463252221](https://cloud.githubusercontent.com/assets/19377624/15276702/45effb22-1af0-11e6-947a-59f5576ba2e6.jpg)
![post-133-0-52306700-1463252265](https://cloud.githubusercontent.com/assets/19377624/15276704/4e183990-1af0-11e6-9fb3-e43b57445bc7.jpg)

**Comment by p1pkin** [comment]
it seems 2003 Rev.A version have slightly different inputs wiring.
will be ok in next release.

**Comment by RAMBO123654** [comment]
Thank you,
You are the best.
