### ISSUE TITLE
Hydro Thunder multiplayer flickering

### ISSUE THREAD

**Issue by JacobAL** [p1pkin/demul#368]
Hydro Thunder works great but has this annoying flickering in multiplayer, regardless of what video plugin is being used. It's 100% playable but this graphical glitch is rather irritating.
Youtube video attempting to capture it:  https://www.youtube.com/watch?v=QSUXVXs2nx0
Graphics settings are shown at the end of the video. I have played around with hacks and settings in the past and nothing has helped.
Specs: http://i.imgur.com/lk2EKwH.png

**Comment by p1pkin** [comment]
thanks, I'll look at this

**Comment by p1pkin** [comment]
use latest emulator build with default DX11 renderer

**Comment by JacobAL** [comment]
Thanks. I've tried the new build and it did work quite a bit better on the old renderer as well.
