### ISSUE TITLE
Metal Slug 6 Crashes

### ISSUE THREAD

**Issue by lexterror** [p1pkin/demul#369]
I'm pretty sure it's a "Video Plugin" problem: Whenever I'm playing "Metal Slug 6" it always crashes. The emulator shows GPU FPS as "0" at the time of each crash.

My PC is:
-Windows 10 Pro x64
-DX12
-Intel Core i3-5010U
-Intel HD Graphics 5500
-1TB HDD
-6GB RAM

**Comment by p1pkin** [comment]
does it even starts and shows something ?
normally Demul require real graphics card, not that Intel HD thing.

if it crashes during gameplay it may be because of original game bug
https://github.com/p1pkin/demul/issues/223

**Comment by lexterror** [comment]
It turns out the problem was "shooting while pressing L+R" I really appreciate your help.
Thank you
