### ISSUE TITLE
demul 0582: dc version of Cacpom vs snk 2 unplayable on netplay

### ISSUE THREAD

**Issue by apathy27** [p1pkin/demul#373]
is the dc version of Capcom vs snk 2 unplayable on netplay (kaillera P2P) on demul builds beyond 0.5.6? i've tried it on demul 0.5.8.2 , 07a_221215 & 07a_160818 but whenever me and my friends connect on kaillera p2p the game screen just remains black and won't go any further...it works on 0.5.6 but even offline it lags and stutters a lot on that version...

**Comment by p1pkin** [comment]
fast network connection required.
its not "just remains black" but synchronizing non-voltage memory(s), flash in the case of Dreamcast games, using kaillera. it will be very long/slow if you have slow and/or high latency network connection.

**Comment by apathy27** [comment]
but the naomi version of the game connects just fine

**Comment by apathy27** [comment]
and i have a 1mbps connection too

**Comment by p1pkin** [comment]
Naomi games needs to sync (transfer from host to peer(s)) 32KB of data, for Dreamcast games it is 4x bigger - 128KB, this makes significant difference, because data transfer via kaillera very very slow.
I'm afraid 1mbps is not enough.

**Comment by p1pkin** [comment]
old Demul versions, like 056, require manual non-voltage data sync, ie players must take care by yourself to use exact same dc.flash files for dreamcast and .sram / .eeprom files for Naomi games.
newer Demul versions, 058 and above, do this automatically, but kaillera is rusty old piece of shit and not designed to transfer data using it, so it is require quite fast connection for transfer just few hundreds of kilobytes.

**Comment by apathy27** [comment]
so exactly how much internet speed is required Dreamcast games?

**Comment by p1pkin** [comment]
have no idea, can say only - it works fine for me here, with 100mbps

**Comment by apathy27** [comment]
k...i though it all depended on kaillera since on Epsxe Cyberpad kaillera
connected, started the game and played quite well with no lag, with me
being in india and my friend in France. And we played Street Fighter EX2plus

**Comment by p1pkin** [comment]
did you read my previous messages at all?
its not during gameplay, but transfering dreamcast flash from host to peer.
PS1 have no such flash, so there no need for such sync in epsxe.

**Comment by apathy27** [comment]
i know im just saying...didn't expect it to be so complex

**Comment by p1pkin** [comment]
okay, well, its actually simple, but shitty kaillera have no (sane) way for data transfering.

so it will be as is, unless replaced by some different networking system.

**Comment by apathy27** [comment]
will it be possible to improve demul to reduce the bandwidth requirement
for dc games?

**Comment by p1pkin** [comment]
I see no reason to waste time on this.
much better get rid of kaillera stinky shit

**Comment by apathy27** [comment]
so then are u thinking of an alternative for demul netplay?

**Comment by p1pkin** [comment]
for recent future - nothing, haven't interest in it

**Comment by apathy27** [comment]
is it possible to use netblade plugin with demul versions after 0.5.6?
