### ISSUE TITLE
marvel vs. capcom 2 naomi demul 8-18-2016

### ISSUE THREAD

**Issue by jmodlin210** [p1pkin/demul#377]
I noticed that guile's hair and face is messed up for the characters intro in marvel vs. capcom 2 naomi demul 8-18-2016

**Comment by jmodlin210** [comment]
https://www.youtube.com/watch?v=7o1DiUQlqeo for marvel vs. capcom 2 naomi intro about guile's hair and face is messed up for characters intro in demul 8-18-2016.

**Comment by p1pkin** [comment]
will be ok in next build

**Comment by jmodlin210** [comment]
What will be okay in the next build of demul and wanted guile's hair and face fixed for the characters intro in marvel vs. capcom 2 naomi intro. when will the next build be released?

**Comment by p1pkin** [comment]
I told you already - tomorrow or next year or never.
