### ISSUE TITLE
gpuDX11old white screen

### ISSUE THREAD

**Issue by ENunn** [p1pkin/demul#380]
So I want to have higher internal resolutions, but it doesn't work with the new plugin. I chose the old plugin but I get a white screen.
![desktop 9-11-2016 8-30-38 am-357](https://cloud.githubusercontent.com/assets/19480682/18417580/0f1e76f2-77fa-11e6-9c2d-0f5b398c4ec5.png)

Any help?

**Comment by p1pkin** [comment]
well, old renderer is discontuned for years, so there any kinds bad emulated things, glitches or crashes expected. its miracle it somehow works at all for some people.
