### ISSUE TITLE
Suggestion - OpenGL renderer 

### ISSUE THREAD

**Issue by RinMaru** [p1pkin/demul#381]
so any plans for this?

**Comment by p1pkin** [comment]
but why ?

**Comment by jmodlin210** [comment]
i want opengl renderer for demul to make graphics and image look smooth.

**Comment by RinMaru** [comment]
well it would make it easier on linux through wine, its supported on more systems, its arguably easier to use, and faster some might say.

**Comment by p1pkin** [comment]
sorry, but dev. team have no people interested in Linux.
in my opinion OpenGL is sort of "dead end" API, can't see good reasons to use it in 2016.
also it is _MUCH_ (5x - 10x) slower than Direct3D11 in "Order Independent Translucency" implementations which had Dreamcast/NAOMI/etc PowerVR2 GPU and required for it's correct emulation..

**Comment by RinMaru** [comment]
anyways thanks for your answers. i plan to use this if reicast don't get proper windows gui and gamepad support. plus Demul seems to have a dedicated team not letting it die.

**Comment by p1pkin** [comment]
welcome.
sorry to say but during last 2-3 years old team members is almost inactive, so everything was developed by single person in latest v0.7 releases...

**Comment by RinMaru** [comment]
thats sad to hear U_U i just hope the best because this has been in dev for a good while and i tested it while nulldc was in dev. so i have hopes this pulls through because allot of dc emus are dead. 
Redream and Reicast are all thats left besides Demul.
