### ISSUE TITLE
marvel vs. capcom 2 naomi score ranking display bug 

### ISSUE THREAD

**Issue by jmodlin210** [p1pkin/demul#383]
![20160911_165543](https://cloud.githubusercontent.com/assets/22105571/18420457/0e5f661c-7841-11e6-90f0-327aa5ed067a.jpg) that there is a bug for marvel vs. capcom 2 naomi score ranking display that flickers on and off on demul 8-18-2016 and can you please fix it for the next build of demul?

**Comment by p1pkin** [comment]
fix what ? afaik it flickers on real NAOMI as well.
