### ISSUE TITLE
Street Fighter Alpha 3 Dreamcast

### ISSUE THREAD

**Issue by Naccarato** [p1pkin/demul#385]
During the Capcom intro for the game, where the logo spins around, the audio becomes choppy with weird audio pitches.  This happens when V-sync is active.  Not sure if this intro is present in the Naomi version.

**Comment by p1pkin** [comment]
does this happens at first game run or at each ?
cant reproduce it here...
likely its something GPU-drivers related, and require to disable power saving for Demul in driver settings, otherwise it will lower yours video card clock to very low values so emulator cant work at full speed.

**Comment by Naccarato** [comment]
It starts when the game firsts loads; the capcom logo does a spin animation and then zooms out.  This is only when V-sync is enabled.  I forgot to mention that I notice the frame counter drop at that scene.  So there's a CPU/GPU spike in usage.  I'll take a look into the drivers when I get home.  
System
2700 i7
GTX 960 Ti 1gb
16gb ram

**Comment by p1pkin** [comment]
that GPU renderer you use ?
gpuDX11old indeed have stuttering during Capcom logo at every game launch, and the logo itself drawn incorrectly with artifacts.
but using gpuDX11 I haven't mentioned issues.

**Comment by Naccarato** [comment]
I'm using the regular gpuDX11.  Is my GPU too weak maybe?  What settings are you trying yours on?

**Comment by p1pkin** [comment]
I'd say vice versa - my system is less powerful, have i5 760 with HD6870 here.
so its really looks like drivers power saving issue, it may sound odd, but more powerful GPU you have - then more chances drivers decide switch to '2D' clocks then Demul running, and lead to stuttering in result.

as was said - create profile in NV drivers settings for Demul and switch power saving option to 'use maximum performance', in most cases this solves similar issues.

**Comment by Naccarato** [comment]
That worked.  Thanks!  Do you think you can mention this in the documentation for the next release?  Or is there a way to let the drivers know not to lower the gpu?

Off-topic: How are feature requests created?  Just submit them to the issue list?

**Comment by p1pkin** [comment]
English documentation is in TODO list, but atm here no people with enough language knowledge for this.
no, there no way from application to tell drivers not use power saving. in the case of AMD videocards its even worse - theirs drivers doesn't have option to disable auto power saving.

yes, feature requests can be submit here as well.
