### ISSUE TITLE
Resident Evil Code Veronica Dx11old crash

### ISSUE THREAD

**Issue by psennermann** [p1pkin/demul#386]
Using the Dx11old plugin on DEmul v0.7A 180816, Resident Evil Code Veronica crashes during the first level, if you try to open the map in the stage after the 3rd cutsene of the game (the one when you meet Steve): map shows up, but when you close it and try to return to game, Demul crashes with message "Demul has stopped working".
Also note that:
- Disabling Translucent modifier let you close the map, but after 30 to 60 seconds Demul crashes anyway
- Disabling Translucent modifier and Opaque modifier fixes the problem (but you get no shadows at all)
- DEmul v0.7A 221215 has a slightly different behaviour: it doesn't crash immediately no matter if Translucen modifier is enabled or not, anyway to avoid the "delayed crash" Opaque modifier (shadows) still has to be disabled
- Dx11 plugin doesn't seem to crash at all (but it's low res)

**Comment by p1pkin** [comment]
sorry, but DX11old plugin is old and not maintained for several years, any kinds of glitches or crashes is expected, its miracle it somehow works at all...

**Comment by psennermann** [comment]
Well, are you sure it's a good idea to not maintain the plugin that can offer a superb 3D hi-res resolution?
No offense, but due to the lack of IR scaling, at the moment the new one seems more useful for 2D games than anything else...

**Comment by p1pkin** [comment]
yes I'm sure.
simply speaking "old" plugin have quite shitty and incomplete emulation, but becuse of this was possible to implement simple enough hacks like IR scaling.
"new" plugin have more complete emulation, but old IR hacks wont work anymore, there needed _much_ more complex 'scaling' system implementation, and I have no motivation to waste my time on it.

**Comment by psennermann** [comment]
Ok, ok, but I don't think that finding a way to get HD graphic with the new plugin would be a waste of time...in fact in my opinion at the moment the two main (or only?) "problems" of Demul are tha lack of IR selection in the new plugin and the "first-time-stuttering" due to shadercache creation (the same problem that plagues Dolphin).

**Comment by p1pkin** [comment]
well, we have different motives :)
I'm hobby researcher and programmer, so main things interesting for me discover how some new or unknown things works and implement theirs emulation in Demul, because its fun. as a side effect other people can play games using it ))
but coding some IR scaling or image filters or some gamepad/racing controller/etc support is not fun.

**Comment by psennermann** [comment]
Ok, thanks for what you're doing ;-)
