### ISSUE TITLE
Add cheating feature on DEMUL

### ISSUE THREAD

**Issue by ElektroStudios** [p1pkin/demul#387]
About this feature request:
[Feature Request: Add built-in cheat support #80](https://github.com/p1pkin/demul/issues/80)

One year elapsed from that request, and many more years elapsed from the first DEMUL release... there is any news about this basic and one of the most important features that a console emulator must have?. If a request is "Accepted", it should be considered to be implemented at least in less than one entire year, don't you think so?.

Actually we should follow a serie of tricky steps to apply a cheat, firstly open CheatEngine, attach it to demul, etc, and reproduce the same with ArtMoney... that is just a very pity wate of time to use a damn cheat on a console emulator.

Chankast emulator has its unnofficial "ChankastCheater.exe" application that help users to use cheats, and we are talking of a discontinued project of year 2005, so its incredible that a continued project like DEMUL doesn't have any of this that other console emulators of the past have today. DEMUL developers could even analyze the "ChankastCheater.exe" to accelerate the implementation of this basict must-have feature...

I really can't udnerstand why one year elapsed without any advance on this request (that other miles of users are requesting in silence too), one entire year!!!

**Comment by RinMaru** [comment]
The dev team is small dude and they have other junk to take care of. if you want cheat support so bad make it yourself, otherwise be happy this emu is still active.

**Comment by p1pkin** [comment]
short answer - there no developers who wish to implement this thing for you.

I close this as duplicate #80

**Comment by ElektroStudios** [comment]
@p1pkin 

Then you, are you really saying that you don't wish to implement cheating support as one of the developers of a console emulator project?, really you don't wish to do that? how you can think in that way if you consider yourself a old-skool gamer?.

Well.. nothing more to say mate, this is closed and as you said the devs. will never think to implement that, but just remember this is not only for me, is for EVERYONE, and I think you could speak with better manners when answering a request, sure I could have better respect in other emulator projects that supports cheats...

Regards.
