### ISSUE TITLE
Shenmue audio bug

### ISSUE THREAD

**Issue by bryonsmothers** [p1pkin/demul#391]
I am using demul07a_221215 there seems to be a audio bug where the sound cuts out then back in on cut scenes. This only happens when played in full screen. Window mode works fine.

**Comment by p1pkin** [comment]
does this happens using latest available emulator version (18.08.2016) ?

**Comment by bryonsmothers** [comment]
Its fixed with the latest thank you..

**Comment by p1pkin** [comment]
welcome
