### ISSUE TITLE
Max serve bug — Virtua Tennis 2 (PAL) and Sega Sports Tennis 2K2 (NTSC)

### ISSUE THREAD

**Issue by JustinAyers** [p1pkin/demul#397]
I own a Dreamcast and 2K2 and I can say with certainty that this is a bug in the emulation. 

With both CPU modes it is almost impossible to get "maximum power" on the serve with the male player in the bowling pins practice area in the Career Mode. The result is that the player cannot be developed fully because his serve speed will remain very slow — ruining the Career Mode. I maxed out serve control but spent many hours trying to raise his serve speed only to make it to level 5 out of 22 before giving up. By contrast, it's unusually easy to get maximum serving speed with the female character. I got the female maxed out quickly.

This picture shows what the max serve looks like:

https://s15.postimg.org/54864djvf/max_serve.jpg

The oddest part of this is that the male can get maximum serve speed in matches, although not as easily as the female. It's slightly easier to get it in the bowling pin trainer with the CPU set to the slow mode but it's still bugged. I've raised six sets of characters to max in all areas of training on my actual Dreamcast and raising serving speed is normally one of the easier things to do in training.

I have used demul versions 07a_180816 and 0582. 
The games are gdi/chd. 
I am using a Playstation 1 dual shock controller with a USB adapter from Radio Shack.
My system is Windows 10 Anniversary with a stock i7 6700K, 3200 RAM, and a GTX 1070.

update:

I did more testing and the issue exists with Virtua Tennis and 2K2. I tried changing video settings and the BIOS. I'm also having problems with new sets of characters getting to max, regardless of whether it's male or female — even in matches. This is different than yesterday where my female character in Virtua Tennis was able to easily get max speed over and over again. There is clearly a glitch somewhere. Yesterday I mainly was using demul 0582, though. Today I was using the latest alpha.

**Comment by p1pkin** [comment]
is there exists an easy way to reproduce this issue and compare real VS emulated ?
I havent real DC or NAOMI, so cant compare. however I was able to do several serves at max power, its not easy but not impossible.
