### ISSUE TITLE
Why is wrong?

### ISSUE THREAD

**Issue by qwe9264** [p1pkin/demul#400]
![2](https://cloud.githubusercontent.com/assets/24892066/21605729/f742e61c-d1e5-11e6-9a2e-a66ea9db9ad4.png)

**Comment by p1pkin** [comment]
more details about problem ?
why not use latest emulator version ?

**Comment by danada** [comment]
Late reply, but the error message translates to

> Reading the card failed.

> Please remove the card.

Initial D has a card reader for saving your progress in the game. If you don't have a card, select no `いいえ` or `ない` or something along those lines to tell the game you don't want to use a card.

**Comment by raidenii** [comment]
Since you don't have the card, you should follow the instruction on the second option: press start key.
お持ちでない方：スタートボタンを押してください
