### ISSUE TITLE
Grandia II - Graphical issues

### ISSUE THREAD

**Issue by Redyn** [p1pkin/demul#401]
I just tried Grandia II in Demul and noticed that the scene transition effect when a battle starts is glitched. This is what it's supposed to look like:
https://youtu.be/4ugIIqI5Zp0?t=11m00s

Unfortunately, the effect looks really glitchy in Demul:
http://imgur.com/a/Jf0FZ

In addition, the blur on the models just after the battle begins seems to be missing.

**Comment by p1pkin** [comment]
can't reproduce, screen transition effect before fights looks fine here.
make sure you use normal renderer, not that outdated and glitchy "dx11old" shit.

in general: no reports allowed for DX11old renderer. its discontinued, and have tons of bugs.

**Comment by Redyn** [comment]
Oh, my bad. Forgot I was using the old renderer. The reason I use it is that the new renderer doesn't support non-native internal resolutions. I wasn't aware it was glitchy, though, as this is just about the first graphical issue I've run into.

Say, are there any plans to implement the internal resolution setting in the new renderer any time soon?

**Comment by p1pkin** [comment]
yes, there is plans, technically its possible I think, but it is quite hard and complex, so do not expect it happens anytime soon.

such hacks like renderer resolution scaling was easy enough to implement only then some "internal parts" of PowerVR2 GPU was not emulated at all, like frame buffer in this case.
but the more fully GPU becomes emulated then more hard to add some hacks or features, which original GPU wasn't capable of.
