### ISSUE TITLE
Dead or Alive 2 (PAL) No Sound (TOSEC)

### ISSUE THREAD

**Issue by Catarax** [p1pkin/demul#402]
The redump verified rip of DOA 2 europe doesn't play background music at all (menu, in-game).
I have to use the ReviveDC .cdi file to get it to play.
All others redump games I have play sound like it should.

Using the latest stable release.

I think the issue comes from the size of the file 
![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22355687/74c07494-e42c-11e6-89af-eabc0a6eb0d7.png)

**Comment by p1pkin** [comment]
redump DC images not recommended to use,
GDI format is not designed to store offset corrected audio tracks they use, so basically all GDI images from redump.org can be considered as broken or bad. get TOSEC or Trurip GDIs instead.

**Comment by Catarax** [comment]
Tried on a TOSEC rip, same issue.
Hmm, the ReviveDC cdi I have is the NTSC release.
Seems a problem on the European release only, i'll try on the NTSC TOSEC version soon.

**Comment by p1pkin** [comment]
looks odd, I havent such issue here.
please share your settings and non-volatile data (*.ini files, memsaves and nvram folders )

**Comment by Catarax** [comment]
https://mega.nz/#!vcZizRwS!8B3vnsLQmV3QmliIgtNRS5g5Ax2FIgatZvI9-nmG7Fw

**Comment by p1pkin** [comment]
are you kidding me ? ;)
you have set volume to zero in game audio options
