### ISSUE TITLE
Star Wars Episode I Jedi Power Battle (hang then save to full VMU)

### ISSUE THREAD

**Issue by Catarax** [p1pkin/demul#403]
Game hang when saving after finished the first level. (PAL/TOSEC)

![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22383646/ee3dbd88-e4ca-11e6-8337-b749244dda6d.png)

No save loadable after relaunching Demul.
Using the v0.7 alpha (august)

**Comment by p1pkin** [comment]
can you share your settings and VMU files ? (*.ini files, "memsaves" and "nvram" folders)
can't reproduce it here, save game works for me

**Comment by Catarax** [comment]
All should be there:
https://mega.nz/#!vcZizRwS!8B3vnsLQmV3QmliIgtNRS5g5Ax2FIgatZvI9-nmG7Fw

I think the bug was due to the fact I don't have enough space to save on first controller. (16 blocks required in the back cover)
But the second controller was available when i tried to save.

Let me know, thanks!

**Comment by p1pkin** [comment]
provided VMU doesn't have enough free blocks
as for me it looks like the way this game works, so 1st player can save to VMU inserted into Port A controller only, and hang if there not enough free space.
required someone with real console and full memory card to check this

**Comment by japanese-cake** [comment]
I confirm that it hangs as well on the real hardware when there isn't enough block available on the VMU (I guess the vmu A1).

**Comment by p1pkin** [comment]
@japanese-cake thank you for checking
