### ISSUE TITLE
Taxi 2 (DC) : Modifying in-game music glitchy noise

### ISSUE THREAD

**Issue by Catarax** [p1pkin/demul#404]
Game : Taxi 2 (Le jeu) (Dreamcast) (TOSEC)
Version: Latest stable build (18 aug 2016)

1) Pause the game
2) Choose another track
3) Heavy glitchy noise music will come during 10 sec
4) Woman voice message : "This is a Microsoft CE game for Dreamcast, please do not..."
5) The game can still be played but without background music after

![screenshot_1](https://cloud.githubusercontent.com/assets/3964507/22428455/5aa0fc4a-e707-11e6-86e3-33ca7e313923.png)

Also, the game run more slowly when you play in the first person view.

**Comment by p1pkin** [comment]
fixed, will be OK in next release.
if its critical - as workaround may be used some of 2015 emulator builds, which doesn't have this issue.

**Comment by Catarax** [comment]
Thanks!

**Comment by p1pkin** [comment]
thanks for useful report!
