### ISSUE TITLE
Maken X - Flickering Menu elements

### ISSUE THREAD

**Issue by Krusher97** [p1pkin/demul#406]
Game : Maken X v1.001 (2000)(Sega)(NTSC)(US)[!]
Version: Demul 0.7A 180816

Certain icons in the menu have heavy flickering on the new DX11 plugin. This is not present in the oldDX11 plugin.

[New DX11 video ](https://youtu.be/tRMfhR3sINs)
[Old DX11 video](https://youtu.be/aX_X0QerHgU)

![maken x dx11 new menu](https://cloud.githubusercontent.com/assets/25664221/22786346/1fc1d46a-eefe-11e6-978c-ed469f8726fb.png)

![maken x dx11 old menu](https://cloud.githubusercontent.com/assets/25664221/22786357/2e3b4b3e-eefe-11e6-983a-bff3bddd3b24.png)

Note the sliders in SE and BGM in the top screenshot(which is the new DX11 plugin one)

**Comment by p1pkin** [comment]
thats the reason why video option "Enable Translucent Join" exists.
for games with such artifacts you have to disable this optimisation
(or if you have Nvidia GPU you may disable it forever, there not much if any speed boost for NV)
