### ISSUE TITLE
Fushigi no Dungeon - Fuurai no Shiren Gaiden - Freeze on intro logo

### ISSUE THREAD

**Issue by Krusher97** [p1pkin/demul#407]
Game : Fushigi no Dungeon - Fuurai no Shiren Gaiden - Onna Kenshi Asuka Kenzan! (Japan)
Version: Demul 0.7A 180816

The game does not continue past the intro Sega logo after the Bios logos.

![fushigi](https://cloud.githubusercontent.com/assets/25664221/23555682/dccc3aac-004f-11e7-97ed-576256205914.png)

**Comment by p1pkin** [comment]
regression as of r3331
as workaround you can use 230915 or earlier build

**Comment by Krusher97** [comment]
Seems like a similar issue affects Sonic Adventure as its playable on 230915 but not on 180816

**Comment by p1pkin** [comment]
nope, Sonic Adv is playable, always was.
do not mess with different emulator versions in the same folder, or at least check settings after doing this, likely they will be screwed,
I'd guess you have incorrect DC BIOS set for 180816, revert it back to default 1.01d

**Comment by Krusher97** [comment]
Are you sure you've tested it yourself? I get a black screen for it right after the Sega logo. The emulator reports 0 FPS. Tested it after someone made a post on the forums.
![sonic adventure 180816](https://cloud.githubusercontent.com/assets/25664221/23585675/2d23382e-01aa-11e7-82f5-a1a4b09fc85c.png)

EDIT : This is in 180816 which is in a separate folder from 230915. As I said above, it doesn't happen in 230915.

**Comment by p1pkin** [comment]
yes, sure I've tested it by myself.
installed Demul into empty folder, run it, NOTHING touched in settings, except path to bios roms was added, select any of regular Sonic or Limited edition (both GDI from TOSEC) - works with no any problem.

that game image you are use ?

**Comment by Krusher97** [comment]
Nevermind then. It was probably a VMU issue on my part.

It stated booting again after I deleted the old memory card save.

**Comment by p1pkin** [comment]
ok. so "which is in a separate folder" was a lie ? ;)

**Comment by Krusher97** [comment]
No. It was in a separate folder. It just wasn't a new one. I had been using that to play other games. 

Could you see if setting the Port B to NONE in Maple Device Manager changes anything for you? It seems to be replicating the black screen for me even in a clean folder. I think I might have isolated the issue. 

EDIT: I should probably make a separate issue for this instead of cluttering this one

**Comment by p1pkin** [comment]
its known, and its not only Sonic issue, thats why there enabled 2 controllers by default.
just don't touch it.

**Comment by p1pkin** [comment]
anyway, both mentioned issues will be OK in next release.
this Fushigi game was interesting test case in term of GD-ROM access, thanks for reporting.

**Comment by Krusher97** [comment]
Boots up without any problems in v0.7 171011 from here : http://forum.emu-russia.net/viewtopic.php?f=25&t=503&start=180
Closing this
