### ISSUE TITLE
Option to hide system mouse pointer

### ISSUE THREAD

**Issue by neosquid** [p1pkin/demul#410]
When a game is loaded via Demul, the mouse cursor remains in the middle of the screen.

Please could there be an check box option to hide the mouse cursor in Demul?

Thank you.

**Comment by RinMaru** [comment]
I usually just move the mouse to the far side of the screen but it would be nice to have the mouse hide after a few seconds of inactivity

**Comment by p1pkin** [comment]
but why ?
mouse cursor hidden then in fullscreen (can be shown if F11 pressed), in windowed mode mouse cursor is always shown, wondering why to hide it.

**Comment by neosquid** [comment]
If you are using an DEMUL on a television, it's just convenient not to have to use the keyboard.  Dolphin gamecube/wii emulator has this option.

Nice that F11 exists as an option, didn't know about that.

**Comment by p1pkin** [comment]
still do not understand why such feature needed. people who uses Demul in arcade-like cabinets usually happy with "start in fullscreen" option enabled.

> Dolphin gamecube/wii emulator has this option.

I don't care. I don't like the idea making swiss knife-like software.
