### ISSUE TITLE
metal slug 6 atomiswave random stuck 

### ISSUE THREAD

**Issue by koyuyesil** [p1pkin/demul#412]
stoped working everytime nvidia gtx770 amd fx8350 pc maybe problem osd game dvr or nvidia dvr 0.7 alpha aug 18 2016 program not stopped al menus work but game graphics and sound stop.  same as cardtiridge removed sega mega drive console last frame on screen. sometimes lost graphics 3d games. emulator comple closed and rerun after fixing. maybe wrong adressing rom files.

**Comment by p1pkin** [comment]
duplicate #196 
original game bug: left + right + fire = game hang
