### ISSUE TITLE
Feature request on input plugin: ignore inputs of opposing directions

### ISSUE THREAD

**Issue by raidenii** [p1pkin/demul#413]
Hello,

Is it possible/ok to introduce this feature just like MAME does? In MAME, when user inputs opposing directions simultaneously (e.g., up+down or left+right), MAME will simply ignore them. This fixes/bypasses the bug such as in Metal Slug 6, where inputs left+right+fire together results in game crash.

An example of input processing in MAME is here:
https://github.com/mamedev/mame/blob/master/src/emu/ioport.cpp

```
	// lock out opposing directions (left + right or up + down)
	if ((m_current & (UP_BIT | DOWN_BIT)) == (UP_BIT | DOWN_BIT))
		m_current &= ~(UP_BIT | DOWN_BIT);
	if ((m_current & (LEFT_BIT | RIGHT_BIT)) == (LEFT_BIT | RIGHT_BIT))
                m_current &= ~(LEFT_BIT | RIGHT_BIT);
```

Many thanks.

**Comment by p1pkin** [comment]
duplicate #115
