### ISSUE TITLE
When the Fur Fighters game will be playable?

### ISSUE THREAD

**Issue by Prinzmetal** [p1pkin/demul#414]
Unfortunately it hangs at the start or after entering into various stages. (Black screen).
Thanks!

**Comment by p1pkin** [comment]
this game have Y2K-like bugs. try set console time to 2000, 2001 etc years and play the game, in such case it was reported working by number of players.
feel free to find exact "working" and "non-working" time/date settings if you are fan of this game (I'm not)

**Comment by RinMaru** [comment]
Lol wow a bug that occurs due to a date.

**Comment by Prinzmetal** [comment]
It's soooo weird! But it really works at 2001 yr! Thanks a lot!!
