### ISSUE TITLE
Legacy Of Kain: Soul Reaver Graphics issues

### ISSUE THREAD

**Issue by vandaldx** [p1pkin/demul#417]
This title have much issues.

-Speed is not an issue.
-Soul Spiral (life bar) is glitched and appear nearly totally broken.
-Some trasparency don't show as intended.
-Some effects are glitched (constant claw attack lost the blue trail)
-Sound is little crippled at any configs, some midis finish abruptly and makes the sound inconsistent.

  This emu is great, but some games have glitches that ruin the experience.

**Comment by p1pkin** [comment]
a lot of time has been passed, but still...

can you please give more detailed explanation of following issues ?
> -Some trasparency don't show as intended.
-Some effects are glitched (constant claw attack lost the blue trail)
-Sound is little crippled at any configs, some midis finish abruptly and makes the sound inconsistent.

I've fixed life bar spiral issue but can't see the others.
