### ISSUE TITLE
Legacy of Kain: Soul Reaver save/load state crash

### ISSUE THREAD

**Issue by nebachadnezzar** [p1pkin/demul#418]
I know that Demul crashing when loading saved states is an old issue, but with the new version claiming to "* fix save states crash" I just want to point out that, with this specific game (but probably many others), when trying to load a saved state from a previous sessions, the emulator still crashes.

**Comment by p1pkin** [comment]
thanks for finally reporting. it is game specific issue. you may try latest (171011) build.
speaking in general - save states in Demul is piece of hack, which works by accident, so there might be others cases when it crash or hangs (I'm sure they're there). if you'll notice one of such - report them here (in separate issue).

**Comment by nebachadnezzar** [comment]
It's working in 171011. Problem fixed :)
