### ISSUE TITLE
Possible z-fighting issue? (18 Wheeler)

### ISSUE THREAD

**Issue by 87th-E** [p1pkin/demul#419]
Not sure if this was already mentioned or not, but it occurs on the previous build before the latest one, too. The old GPU plugin doesn't have this issue, but is less accurate (screen transitions are proper with the new plugin). While a screenshot won't show it, the statistic arrow graphics (which is the issue source) flicker immensely. Haven't tested NAOMI version as I haven't configured it yet.

Attached are screenshots using both plugins at default settings and resolution, VSync off:
![2017-10-11_142028](https://user-images.githubusercontent.com/32716300/31458956-a0228ce8-ae8f-11e7-8366-cf3ad0953506.png)
![2017-10-11_142152](https://user-images.githubusercontent.com/32716300/31458957-a0350710-ae8f-11e7-8f6e-f4c2122295ab.png)

Could be debatable as it's a minor issue, but the flickering that occurs is very apparent. Haven't checked any other areas of the game yet.

System specifications if they are applicable:

- Intel Xeon E3-1275L V3 2.6GHz (3.9GHz single thread; 3.7GHz dual-thread)
- Nvidia GeForce GTX 960 2GB (latest drivers)
- 8GB DDR3

**Comment by p1pkin** [comment]
Z-fighting issues often caused by "Enable translucent join" optimization. did you tried to disable it ?

**Comment by 87th-E** [comment]
Disabling "Enable translucent join" fixes the issue:

![2017-10-11_145055](https://user-images.githubusercontent.com/32716300/31460222-a5f1c612-ae93-11e7-9ebf-6182c6fd7bf3.png)

Thank you for your response. As "Enable translucent join" is set to On by default, would this affect any other games with the setting turned off?

**Comment by p1pkin** [comment]
it is speed optimization, without it some games may work slow on older video cards, especially ATI/AMD.
not really needed if Demul run on some modern GPU. I think it will be better have it disabled by default these days.
