### ISSUE TITLE
Derby Owners Club Connect more than one satellite.

### ISSUE THREAD

**Issue by cooperate** [p1pkin/demul#421]
Hello I cannot figure out how to connect more than one satellite instance to Derby Owners Club session.

Same result on Derby owners club and Derby Owners Club World Edition EX

This is as far as I've gotten:
https://i.imgur.com/pxPuqAE.png

**Comment by p1pkin** [comment]
there is no way. this game is not even in "officially" working state, and was not mentioned in changelog. it works mainly thanks to debug/wip implementation, there number of sattelite units hardcoded to 1 only,

**Comment by cooperate** [comment]
@p1pkin 
I figured as much, thanks for the response though!
