### ISSUE TITLE
Star Wars Episode 1 Racer (Anakin 2 player missing character)

### ISSUE THREAD

**Issue by Catarax** [p1pkin/demul#422]
![screenshot_1](https://user-images.githubusercontent.com/3964507/31575881-59b86d6e-b0f0-11e7-88e3-d2e4843a2ccd.png)
It happens only in 2 player mode, the Anakin character is missing in his pod, also if you use him as the second player.

TOSEC rip, PAL, latest demul (12 october), modern D3D11 plugin

**Comment by p1pkin** [comment]
is Anakin character visible on real Dreamcast in 2 player mode ?

**Comment by Catarax** [comment]
Ok, tried on original hardware, Demul is accurate, guess it's a bug from the Dreamcast port only.

**Comment by p1pkin** [comment]
wow, thank you very much for checking!
does screen splitting looks same buggy as well on real Dreamcast ? ie part of upper screen is visible below black divider bar (in PAL version, but it is fine in NTSC). and player positions icons "1" and "2" have same strange background ?

**Comment by Catarax** [comment]
Checked again, it's accurate funilly, i'm playing on 480p on both console.
Will have a look on the NTSC version, thanks!

**Comment by p1pkin** [comment]
thanks one more time for checking
