### ISSUE TITLE
issues with Atomiswave games GFX clipping 

### ISSUE THREAD

**Issue by DataCenterNinja** [p1pkin/demul#424]
Noticed that MSlug 6 and Dolphin Blue had weird artifacts with Demul v0.7 171012.  Metal Slug 6 only seemed to show NPC sprites and Dolphin Blue was causing certain areas of the screen to become transparent (clipping).  My machine is Windows 7 with Nvidia 1050Ti (current drivers).  Games work fine with v.7A (Auguest 2016)

**Comment by p1pkin** [comment]
what renderer do you use, regular one or outdated old ?
try to delete shader cache (scache) folder.
