### ISSUE TITLE
[regression] Gunlord doesn't work anymore

### ISSUE THREAD

**Issue by nebachadnezzar** [p1pkin/demul#425]
When trying to boot Gunlord, demul crashes with the following error:

"Microsoft Visual C++ Runtime Library

Runtime error!

Program:

This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information."

This happens both in version 171010 and 171012, but the game was working fine in version 160818.

**Comment by p1pkin** [comment]
forgot to disable some diagnostic code, with doesnt like this game. will be OK in some next build.

**Comment by nebachadnezzar** [comment]
Ok, good to know :)

**Comment by p1pkin** [comment]
np, thanks for report

**Comment by nebachadnezzar** [comment]
The game now works great but I've found an interesting bug. It's not serious, but it might be important for the internal workings of the emulator so I'll write it here anyway. If you have a lightgun as controller two (maybe the same happens with other peripherals, in my case it was a lightgun) the game behaves as if you're pressing a lot of buttons at the same time and is impossible to play. Changing the second controller to nothing fixes it.

**Comment by p1pkin** [comment]
looks more like game bugs. we need someone with real DC and lightgun to check this.
