### ISSUE TITLE
Can you guys open up a Patreon and reap the benefits of the current emulation-friendly lanscape?

### ISSUE THREAD

**Issue by ghost** [p1pkin/demul#426]
Hi.

The [**CEMU Team**](https://www.patreon.com/cemu) and the [**RPCS3 Team**](https://www.patreon.com/Nekotekina) are both using [**Patreon**](https://www.patreon.com) to rake in the dough and advance their respective offerings by leaps and bounds.

The DEMUL Team should do the same.

Just a thought.

Cheers.

**Comment by RinMaru** [comment]
While i think this is a great idea to encourage work... Im not going to act like i know whats going on but I dont see them doing this

**Comment by ghost** [comment]
**RinMaru** commented:
> _While i think this is a great idea to encourage work...  Im not going to act like i know whats going on but I dont see them  doing this_

Oh, didn't know there were any kind of rules regarding this project.

Message for the devs:
> **If you feel this is worth considering, neat; if not, I apologise for butting in, and please feel free to close this as a non-issue.**

Cheers.

**Comment by RinMaru** [comment]
nah no rules Ive just always got the impression that the devs aren't interested in any of that otherwise I think they would have considered it awhile back

**Comment by p1pkin** [comment]
in short - I'm very negative to sponsored emulators development like Patreon or similar.
in my opinion sooner or later such "sponsored development" may lead to legal actions, like we seen recently Atlus v. RPCS3, in worst case it may create a precedent basis in US law, and jeopardize the legal status of creating emulators in general.
I think everyone who acting like for example Cemu developers is mindless fools, and putting in danger whole game preservation community and idea.

If anyone wants "say thank you" for Demul development in form of money - you may donate to "The Dumping Union"
http://www.mameworld.info/ubbthreads/showthreaded.php?Number=311481
it is small group of people, me including, who spending own time and money for arcade games preservation (usually it is hundreds or thousands of USD per month in total). some donations may help us in getting preserved more NAOMI, Gaelco, etc arcade games.

**Comment by Logitech-byte** [comment]
Patreon is pure cancer. Thank god is not in there.
