### ISSUE TITLE
Wrong controls for Alien Front

### ISSUE THREAD

**Issue by GeraBlackHnd** [p1pkin/demul#428]
In my test alien front is locking in right move, other games works nice. I am testing demul 171012.

**Comment by p1pkin** [comment]
did you tried to calibrate controls in game service mode ?
it must be done for almost all games, which uses analog inputs

**Comment by GeraBlackHnd** [comment]
Dont works for me. In mode test is apparentily normal, but in game only right direction works.

**Comment by p1pkin** [comment]
you didn't answer the question - did you calibrated controls in game test mode - controller settings menu ?
after calibration procedure it must become like on screenshot below
![alien_f](https://user-images.githubusercontent.com/2674348/31623442-2118dfd4-b2a8-11e7-8914-32f1b4f66cf2.png)
if you don't do this - there will be all 0 by default, and game will not function correctly.

**Comment by p1pkin** [comment]
in general - arcade games is not like console games "insert disk or cartridge, press start and it will run". in arcade gaming machines often required read machine technical manual and do specific actions by technician personnel.

**Comment by GeraBlackHnd** [comment]
Thanks, works nice!
