### ISSUE TITLE
Block screensaver while running

### ISSUE THREAD

**Issue by jernejs** [p1pkin/demul#434]
Demul currently doesn't prevent Windows from locking the session while it's running, which is a bit annoying during long cutscenes.

**Comment by p1pkin** [comment]
user may tweak windows power management settings as per personal taste. that's why they exists.
wontfix.

**Comment by jernejs** [comment]
That's a pretty stupid response. I've got screen set up to turn off after 5 minutes, because that's what I want normally, however every multimedia app (this includes games, video players and other emulators) overrides this automatically, because while you normally don't normally interact with the computer during cutscenes, it's not actually idle (and because they know it's annoying if you have to remember to move the mouse/press a key every now and then).
