### ISSUE TITLE
Marvel vs. Capcom 2: New Age of Heroes NAOMI score ranking display title flickering

### ISSUE THREAD

**Issue by jmodlin210** [p1pkin/demul#441]
The score ranking display title has been flickering on and off and it doesn't stop for Marvel Vs. Capcom 2: New Age of Heroes Naomi and it is suppose to be of score ranking display title not flickering for Marvel vs. Capcom 2: New Age of Heroes Naomi and be normal.

**Comment by p1pkin** [comment]
isn't it works this way too on real NAOMI or Dreamcast ? should be visible if VGA display used

**Comment by jmodlin210** [comment]
naomi with score display title flickering on and off for marvel vs. capcom 2: new age of heroes and suppose to be score displaying title not flickering.

**Comment by p1pkin** [comment]
okay, looks like real bug. which GPU brand you have, Nvidia or ATI/AMD ?

**Comment by jmodlin210** [comment]
I have nvidia georforce gtx 660m for Asus laptop.

**Comment by p1pkin** [comment]
thanks. will be OK in next release.
