### ISSUE TITLE
Rayman 2 music issue

### ISSUE THREAD

**Issue by CraigMarduk** [p1pkin/demul#445]
Hi, everyone.

I've tried to play Rayman 2 on Demul 0.7 11 Nov 2017. All is right, except fpr the music. I tried every option with spuDemul, but I couldn't get to work?

Any help?

**Comment by p1pkin** [comment]
so, you have sounds but no music in this game ? very strange. if you use pirated game image try to use original one in gdi format.

**Comment by CraigMarduk** [comment]
Yes, that was the problem. I tried with another image and now worked.

Thank you so much.

**Comment by p1pkin** [comment]
good then
