### ISSUE TITLE
Marvel vs Capcom 2 training mode crash

### ISSUE THREAD

**Issue by violn** [p1pkin/demul#447]
In training mode whenever I press the start button the emulator crashes

**Comment by p1pkin** [comment]
can't reproduce it here, when press start during training I see menu as expected.
is there required specific actions or game image to reproduce this issue ?

**Comment by violn** [comment]
idk

**Comment by violn** [comment]
Here's the crash in action

**Comment by violn** [comment]
Here's some footage from the crash
[Crash.zip](https://github.com/p1pkin/demul/files/1676294/Crash.zip)

**Comment by p1pkin** [comment]
thanks, but 1st necessary step in any bug/issue localization and fixing - reproduce it at developer's PC.
sadly your video doesn't help in this at all.

do you use original GDI game image or some pirated CDI ?
is there was made any settings changes in emulator ?

**Comment by violn** [comment]
I use a gdi and  these are my changed settings
![crash](https://user-images.githubusercontent.com/32370882/35593599-88cc6196-05cd-11e8-86d8-5f7b77a36c28.PNG)
![crash2](https://user-images.githubusercontent.com/32370882/35593604-8b3c6b7e-05cd-11e8-9526-ccd7200bca4d.PNG)
![crash3](https://user-images.githubusercontent.com/32370882/35593608-8dccc776-05cd-11e8-9567-ec5e23f08ecf.PNG)
