### ISSUE TITLE
WAVERUNNER GP auto acceleration bug

### ISSUE THREAD

**Issue by Grabisoft** [p1pkin/demul#453]
Past versions of DEMUL didnt have this problem.
With the UP key you accelerate the vehicle.
I even tried with an XBOX ONE controller, mapping the UP key to the controller, nothing seems to work.

CONFIG/CONSTROLS/ARCADE - JOY1/ MAPPING THE ANALOG1
If i map with the thumbsticks AXIS, the left or right turns WORK NICE.
But the acceleration still doesnt work. the bug persists, and it auto accelerates without control.

But with the newest version of DEMUL. its like the UP key is stuck. even if you delete all controls.

the vehicle auto accelerates without control and you cant even navigate the select track screen because it auto chose the first beginner track. 

PLEASE FIX THIS

**Comment by p1pkin** [comment]
duplicate #446

**Comment by Grabisoft** [comment]
its not duplicate because the other said " it works only if analog axis mapped to it, doesn't work if playing from keyboard. will be fixed in next release.". Meaning that using an axis mapping fixed the issue, but it doesnt. even if you map with an axis stick , the auto acceleratin persists. it doesnt solve the bug.

**Comment by p1pkin** [comment]
its a same issue (i.e. mistake in code), so duplicate.
