### ISSUE TITLE
Enable to start Initial D 3

### ISSUE THREAD

**Issue by janghyunkyu** [p1pkin/demul#457]

**Comment by janghyunkyu** [comment]
when i select  Initial D, I got the error message. What Should I do for it? Is it about demul version???
![default](https://user-images.githubusercontent.com/37365855/37394394-ffdb521e-27b6-11e8-8c62-974de2eaa2aa.PNG)

**Comment by p1pkin** [comment]
if its not clear from message window - you missing this game ROM.
