### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by kim-sama** [p1pkin/demul#468]
All the games I play only get 15 fps, I tried to google ways to fix but I can't find anything
My specs:
RAM: 16 GB
Processor: Intel Core i7
Graphics Card: Nvidia Geforce GTX 1060

**Comment by p1pkin** [comment]
it was self resolved ?

**Comment by kim-sama** [comment]
It was my fault, I didn't have Vsync enabled

**Comment by kim-sama** [comment]
Yes

**Comment by kalawangman** [comment]
Its the same thing for me. Pipkin, why is it choppy if vsync is disabled?
