### ISSUE TITLE
Capcom vs SNK 2 sprite glitching (NaomiGD)

### ISSUE THREAD

**Issue by 100percentfast** [p1pkin/demul#470]
Hi all

When playing cvs2gd (rev a) I'm encountering a lot of sprite glitching that seems centered around the character sprites:

https://i.imgur.com/DUN3AsA.png
https://i.imgur.com/bVDKh0N.png
https://i.imgur.com/ErDlMKu.png

These glitches don't appear to be based on the stage, and don't seem to appear outside of player sprite animations.

**Comment by p1pkin** [comment]
is there a simple way to reproduce this ?

which renderer was used DX11 or DX11old ?

**Comment by 100percentfast** [comment]
I used the Direct3d11 plugin, as far as I can tell.
https://i.imgur.com/TKlpGln.png

the titlebar of the Demul window does say gpuDX11hw, though.

steps to reproduce:

1. download & install cvs2gd.zip from coolrom.com
2. download & install NAOMI.zip from coolrom.com
3. download & install Demul v.7
3. attempt to play without changing ingame settings

I did try switching around rendering options, though- nothing seemed to help.

Could this be a versioning issue?

**Comment by p1pkin** [comment]
configuration screenshot is clearly made from DX11old
can you go to Config - Plugins&paths and set there - Video Plugin - gpuDX11, and then check game again ?

also you may try latest emulator version from there - http://forum.emu-russia.net/viewtopic.php?p=26178#p26178

**Comment by 100percentfast** [comment]
I upgraded to the version you linked, and that seemed to do the trick. Thanks a lot for the help.
