### ISSUE TITLE
Demul stutters on a 144hz monitor

### ISSUE THREAD

**Issue by carlhr93** [p1pkin/demul#471]
So I have two monitors, both 1080p but the secondary is 60hz, my main one is 144hz, when I launch a game with Demul the game looks and launch perfectly fine and the fps are locked and stable at 60 but it feels choppy, then ass soon as I move the Demul window to my 60hz monitor it runs so much smoother..

I've tried with the old video plugin, with the new, with v-sync on and off, with fullscreen option off and on and everything is on default settings.

Is there a way to use it in my 144hz monitor? I can use it with my secondary monitor, no problem, but I'm just used to the input latency and size of the 144hz monitor by now.. 

Sorry if I miss something, this is the first time I use this issue thingy on Github.

**Comment by Hydreigon223** [comment]
You aren't the only one with this issue. Tested Demul on a 144hz monitor once and frames felt choppy. I felt stumped at one point.

**Comment by kalawangman** [comment]
Hey Hydreigon223, whats up?

A lot of systems have this issue, but you know what, I think I found a pretty good solution. You guys should try this new version of RTSS with the frameslice feature. 
Just read a bit about it, pretty easy to implement:
[https://forums.blurbusters.com/viewtopic.php?f=2&t=4173](url)
I can play arcade titles pretty much without vsync lag now(and without any tearing). Im pretty confident it will do the job even on high monitor refresh rates.

**Comment by carlhr93** [comment]
@kalawangman Could you elaborate please? I downloaded the latest beta 7.2.0 Beta 2 and I see you can click the framerate limit text to set it to frametime limit, but nothing else, what did you exactly do?

**Comment by p1pkin** [comment]
this issue is cause of real time sync bug, which is already fixed in current code and will be ok in some next release.

@kalawangman stop posting your "cool tech" advertisements, which is not related in any way to actual problems

**Comment by carlhr93** [comment]
@p1pkin Oh, I see, thank you for answering! One last thing, will you implement bezel support in the future? That would be perfect! Thank you again for the good work!

**Comment by Boviligg** [comment]
Same problem here. It works if i set my monitor to 60hz first, then run demul windowed. But if it's full screen or 144hz etc then it stutters like a mf.
