### ISSUE TITLE
StarLancer Hang after logo demul07_180428

### ISSUE THREAD

**Issue by IceLancerSR** [p1pkin/demul#486]
StarLancer redump, game hands at Windows CE logo. RPS goes to 0 and thats it.
demul07_180428

**Comment by p1pkin** [comment]
can't reproduce reproduce issue using game image from TOSEC.
is there needed specific emulator settings or issue happens with redump.org's image only ?

**Comment by IceLancerSR** [comment]
Nothing specific. Just launch game with default settings for me. previous versions would happen the same. RPS goes to 0 but after a second it comes back and game boots. But here it just stays there
StarLancer v1.002 (2000)(Crave)(NTSC)(US)[!].gdi
5 tracks. redump.
VMU
purpuru
B side same.

**Comment by p1pkin** [comment]
no good ideas then, game boots fine here.
perhaps game bugs ? some WinCE titles have poor design and may hang if VMU have no free space, or not 100% genuine (was edited using a bit buggy PC software like VMUexplorer).

you may try it with new/empty VMU, and delete nvram/dc.flash file

as of redump dumps - all their's GDI images technically bad dumps (not valid GDI images) and not recommended to use.

**Comment by IceLancerSR** [comment]
Ok, i managed to boot game but using VMS only. Doesnt boot with VMU

**Comment by IceLancerSR** [comment]
Thanks, although cant find cause of problem , it has been fixed now and cant reproduce bug again.. Deleted dc flash couple times , game boots now without problems with exact setup as before..Confused.. But it works now. Closing
