### ISSUE TITLE
Feature Request: Death Crimson OX (Naomi) mouse control like other light gun games

### ISSUE THREAD

**Issue by midorilandshdm** [p1pkin/demul#492]
While some light gun games for Naomi emulated in Demul use left mouse to fire and right mouse to reload, Death Crimson OX for Naomi still use offscreen reload though,

**Comment by p1pkin** [comment]
right, unlike most of NAOMI games, Death Crimson use "offscreen reload" method, for this action player should press both mouse buttons.
