### ISSUE TITLE
Shader Effects and Internal Resolution options are greyed out

### ISSUE THREAD

**Issue by lucs100** [p1pkin/demul#498]
Regardless of which settings are selected in the Video Config settings, the Shader Effects and Internal Resolution dropdowns are never selectable. I mainly use the Naomi emulator, and have not changed any other settings.

![image](https://user-images.githubusercontent.com/59773132/85954420-45041980-b945-11ea-869b-e4b48a5ea0f9.png)

**Comment by p1pkin** [comment]
these features is not implemented, so greyed out.
