### ISSUE TITLE
mushik4e Lags unless Disable Auto Sort, but then health disappears

### ISSUE THREAD

**Issue by msbeck** [p1pkin/demul#507]
mushik4e is unplayably slow unless you Disable Auto Sort in the Video settings. But if you do that, then the health bar is sorted on a lower layer of the UI and you can no longer see the current health of any beetle.

Is there a way to manually sort the UI elements so that you can keep Disable Auto Sort checked, but move the health bar to a higher layer?

**Comment by p1pkin** [comment]
no. also this is not support forum.

**Comment by msbeck** [comment]
Sorry, seemed like a bug causing it to run in slow motion which prevented play. Are you suggesting it's caused by hardware specs? (also, _are_ there support forums / where?) Thanks

**Comment by p1pkin** [comment]
I'm suggesting you not any cared to provide even minimal set of information about used software or hardware, so it will look like a bug report. if so, why you expecting anyone will be cared to help you solve your personal problem ?

**Comment by msbeck** [comment]
You are right. My apologies. I was focusing on trying to figure out how to manually relayer UI elements rather than solve the problem of the slow motion in the first place.

Here is my setup:
Demul 0.7
Windows 7
Intel Core i5-3450 3.1GHz 4 cores
8gb RAM
64bit
Intel DirectX10

video cutscenes in the game seem to play video and audio perfectly, but gameplay scenes are incredibly slow and voices are demonic and slow.

I'm guessing the issue is DirectX10 graphics card because demul 0.7 uses DirectX11 now.

**Comment by p1pkin** [comment]
Demul require DirectX 11 class GPU, like 10 years old Radeon HD5870 or Nvidia GTX460 at least, or newer / more powerful models.
sorry, can't help you with your problem. also, as was said - here is not a support forum.

**Comment by msbeck** [comment]
Yes, it's clear that this is not a bug and that it's due to my hardware setup. Thanks for everything you've done to make this game playable.
